apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: forgejo
  namespace: forgejo
spec:
  chart: oci://codeberg.org/forgejo-contrib/forgejo
  targetNamespace: forgejo
  valuesContent: |-
    ingress:
      enabled: true
    gitea:
      admin:
        password: FIXME
      metrics:
        enabled: true
        #serviceMonitor:
        #  enabled: true
